/**
 * Tests for the RootLayout component metadata (app/layout.tsx).
 *
 * We only test the metadata export because RootLayout uses
 * Next.js-specific Google Font imports that aren't available in the
 * test environment.
 */
import "@testing-library/jest-dom";

// Mock next/font/google before importing layout
jest.mock("next/font/google", () => ({
  Geist: () => ({ variable: "--font-geist-sans" }),
  Geist_Mono: () => ({ variable: "--font-geist-mono" }),
}));

import { metadata } from "../app/layout";

describe("RootLayout metadata", () => {
  it("has the correct title", () => {
    expect(metadata.title).toBe("Create Next App");
  });

  it("has the correct description", () => {
    expect(metadata.description).toBe("Generated by create next app");
  });
});
